### ISSUE TITLE
Can you provide us with yolov7 and yolov7-w models?

### ISSUE THREAD

**Issue by cyrusbehr** [Qengineering/YoloV7-ncnn-Jetson-Nano#1]
First of all, thank you so much for this code and project, it is very helpful.

In the repo, you provide us with `yolov7-tiny.bin` and `yolov7-tiny.param`. 
Are you able to also provide us with the converted normal model `yolov7.pt` and more accurate model `yolov7-w6.pt` which can be obtained from [this](https://github.com/WongKinYiu/yolov7/releases/tag/v0.1) official repo. 

I would convert myself, but I'm not sure how I convert in such a way that allows dynamic input shape like your model does.

**Comment by Qengineering** [comment]
I'm afraid I can't help you in the short term due to the busyness with other projects.
You may find this useful: https://github.com/Baiyuetribe/ncnn-models/tree/main/object_dection/yolov7

**Comment by cyrusbehr** [comment]
Nice thank you @Qengineering 
Is that the tool you used to convert the `yolov7-tiny.param` model?

**Comment by Qengineering** [comment]
Didn't have to convert the model. [nihui](https://github.com/nihui) has it in its [model zoo](https://github.com/nihui/ncnn-assets/tree/master/models).

**Comment by cyrusbehr** [comment]
Ok makes sense. Thank you for the info.
