### ISSUE TITLE
yolov5 result is better

### ISSUE THREAD

**Issue by lucasjinreal** [Qengineering/YoloV7-ncnn-Jetson-Nano#2]
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/21303438/205899828-0860745b-02f1-48f5-b919-d0ee23ae5e9b.png">

**Comment by Qengineering** [comment]
Which type of YoloV5 are you using (tiny, small)? And which version? 
nihui as used version 3.1 of ultralytics YoloV5. 
Recently version 7.0 has been released. I'm planning to write the interface for ncnn as the topology is quite different. 
BTW, even better than your yolov7_d2?
